language: node_js
node_js:
  - "7.10"
  - "8"
  - "9"
services:
  - mongodb
install:
  - npm install
  - npm run build
before_script:
  # make sure, mongodb is up and running
  - sleep 15
script:
  - npm run lint
  - npm run test:coverage
